import json
import os
import sys
from pathlib import Path
from src.main import main
from src.version import __version__
from src.config import load_config


def show_help():
    print("Mr-Robot CLI")
    print("")
    print("Usage:")
    print("  python3 -m src.cli run")
    print("  python3 -m src.cli version")
    print("  python3 -m src.cli info")
    print("  python3 -m src.cli status")
    print("  python3 -m src.cli status-json")
    print("  python3 -m src.cli config")
    print("  python3 -m src.cli init")
    print("  python3 -m src.cli doctor")
    print("  python3 -m src.cli bootstrap <project-name> <template>")
    print("  python3 -m src.cli help")
    print("")
    print("Templates:")
    print("  python-cli")
    print("  python-library")
    print("  docs")
    print("  automation-tool")


def run():
    main()


def version():
    print(__version__)


def info():
    print("Project: Mr-Robot")
    print(f"Version: {__version__}")
    print("Platform: iPhone + iSH + GitHub")
    print("Type: Structured Python project repository")
def get_status_checks():
    return {
        "Source": os.path.exists("src/main.py"),
        "CLI": os.path.exists("src/cli.py"),
        "Tests": os.path.exists("tests/test_main.py"),
        "Docs": os.path.exists("docs/usage.md"),
        "Roadmap": os.path.exists("docs/roadmap.md"),
        "Architecture": os.path.exists("docs/architecture.md"),
        "Requirements": os.path.exists("requirements.txt"),
        "Makefile": os.path.exists("Makefile"),
    }


def status():
    checks = get_status_checks()
    print("Mr-Robot status")
    print("")
    for name, ok in checks.items():
        state = "OK" if ok else "MISSING"
        print(f"{name}: {state}")


def status_json():
    checks = get_status_checks()
    print(json.dumps(checks, indent=2))


def config():
    values = load_config()
    print("Mr-Robot configuration")
    print("")
    for key, value in values.items():
        print(f"{key}: {value}")


def init():
    Path("data").mkdir(exist_ok=True)
    Path("logs").mkdir(exist_ok=True)
    Path("data/.gitkeep").touch(exist_ok=True)
    Path("logs/.gitkeep").touch(exist_ok=True)
    print("Mr-Robot initialization complete.")
    print("Created: data/, logs/")


def doctor():
    checks = {
        "src/main.py": os.path.exists("src/main.py"),
        "src/cli.py": os.path.exists("src/cli.py"),
        "src/config.py": os.path.exists("src/config.py"),
        "src/version.py": os.path.exists("src/version.py"),
        "tests/test_main.py": os.path.exists("tests/test_main.py"),
        "tests/test_version.py": os.path.exists("tests/test_version.py"),
        "docs/usage.md": os.path.exists("docs/usage.md"),
        "docs/installation.md": os.path.exists("docs/installation.md"),
        "requirements.txt": os.path.exists("requirements.txt"),
        "Makefile": os.path.exists("Makefile"),
        ".env.example": os.path.exists(".env.example"),
    }

    print("Mr-Robot doctor")
    print("")

    failed = []

    for name, ok in checks.items():
        state = "OK" if ok else "MISSING"
        print(f"{name}: {state}")
        if not ok:
            failed.append(name)

    print("")
    if failed:
        print("Doctor result: issues found")
    else:
        print("Doctor result: all checks passed")
def write_common_files(base: Path, project_name: str):
    created = []

    (base / "assets").mkdir()
    created.append("assets/")

    (base / "examples").mkdir()
    created.append("examples/")

    (base / "docs").mkdir()
    created.append("docs/")

    (base / ".env.example").write_text("APP_ENV=development\nAPP_DEBUG=false\n")
    created.append(".env.example")

    (base / "README.md").write_text(
        f"# {project_name}\n\nGenerated by Mr-Robot bootstrap.\n"
    )
    created.append("README.md")

    return created


def bootstrap_python_cli(base: Path, project_name: str):
    created = []

    (base / "src").mkdir()
    created.append("src/")

    (base / "tests").mkdir()
    created.append("tests/")

    (base / "requirements.txt").write_text("pytest\n")
    created.append("requirements.txt")

    (base / "Makefile").write_text(
        "run:\n\tpython3 -m src.main\n\n"
        "test:\n\tpytest\n"
    )
    created.append("Makefile")

    (base / "src" / "__init__.py").write_text("")
    created.append("src/__init__.py")

    (base / "src" / "main.py").write_text(
        "def main():\n"
        f"    print({project_name!r} + ' initialized.')\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )
    created.append("src/main.py")

    (base / "tests" / "__init__.py").write_text("")
    created.append("tests/__init__.py")

    (base / "tests" / "test_main.py").write_text(
        "from src.main import main\n\n\n"
        "def test_main(capsys):\n"
        "    main()\n"
        "    captured = capsys.readouterr()\n"
        f"    assert captured.out.strip() == {project_name!r} + ' initialized.'\n"
    )
    created.append("tests/test_main.py")

    (base / "docs" / "usage.md").write_text(
        "# Usage\n\n```bash\npython3 -m src.main\n```\n"
    )
    created.append("docs/usage.md")

    return created
def bootstrap_python_library(base: Path, project_name: str):
    created = []
    package_name = project_name.replace("-", "_")

    (base / "src").mkdir()
    created.append("src/")

    (base / "tests").mkdir()
    created.append("tests/")

    (base / "requirements.txt").write_text("pytest\n")
    created.append("requirements.txt")

    (base / "Makefile").write_text("test:\n\tpytest\n")
    created.append("Makefile")

    (base / "src" / "__init__.py").write_text(
        '__all__ = ["hello"]\n'
        '__version__ = "0.1.0"\n\n'
        "from .core import hello\n"
    )
    created.append("src/__init__.py")

    (base / "src" / "core.py").write_text(
        "def hello():\n"
        f"    return 'Hello from {package_name}'\n"
    )
    created.append("src/core.py")

    (base / "tests" / "__init__.py").write_text("")
    created.append("tests/__init__.py")

    (base / "tests" / "test_core.py").write_text(
        "from src.core import hello\n\n\n"
        "def test_hello():\n"
        f"    assert hello() == 'Hello from {package_name}'\n"
    )
    created.append("tests/test_core.py")

    (base / "docs" / "usage.md").write_text(
        "# Usage\n\n```python\nfrom src.core import hello\n\nprint(hello())\n```\n"
    )
    created.append("docs/usage.md")

    (base / "pyproject.toml").write_text(
        "[project]\n"
        f'name = "{project_name}"\n'
        'version = "0.1.0"\n'
        f'description = "{project_name} library"\n'
        'readme = "README.md"\n'
        'requires-python = ">=3.9"\n\n'
        "[tool.pytest.ini_options]\n"
        'testpaths = ["tests"]\n'
        'pythonpath = ["."]\n'
    )
    created.append("pyproject.toml")

    return created


def bootstrap_docs(base: Path, project_name: str):
    created = []

    (base / "requirements.txt").write_text("")
    created.append("requirements.txt")

    (base / "docs" / "index.md").write_text(
        f"# {project_name} Documentation\n\n"
        "## Sections\n\n"
        "- Overview\n"
        "- Usage\n"
        "- Notes\n"
    )
    created.append("docs/index.md")

    (base / "docs" / "usage.md").write_text(
        f"# Usage\n\nThis is a documentation-first repository for **{project_name}**.\n"
    )
    created.append("docs/usage.md")

    (base / "Makefile").write_text(
        "preview:\n\t@echo 'Documentation repository ready.'\n"
    )
    created.append("Makefile")

    return created
def bootstrap_automation_tool(base: Path, project_name: str):
    created = []

    (base / "src").mkdir()
    created.append("src/")

    (base / "tests").mkdir()
    created.append("tests/")

    (base / "data").mkdir()
    created.append("data/")

    (base / "logs").mkdir()
    created.append("logs/")

    (base / "requirements.txt").write_text("pytest\n")
    created.append("requirements.txt")

    (base / "Makefile").write_text(
        "run:\n\tpython3 -m src.main\n\n"
        "test:\n\tpytest\n"
    )
    created.append("Makefile")

    (base / "src" / "__init__.py").write_text("")
    created.append("src/__init__.py")

    (base / "src" / "main.py").write_text(
        "def main():\n"
        f"    print({project_name!r} + ' automation tool ready.')\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )
    created.append("src/main.py")

    (base / "tests" / "__init__.py").write_text("")
    created.append("tests/__init__.py")

    (base / "tests" / "test_main.py").write_text(
        "from src.main import main\n\n\n"
        "def test_main(capsys):\n"
        "    main()\n"
        "    captured = capsys.readouterr()\n"
        f"    assert captured.out.strip() == {project_name!r} + ' automation tool ready.'\n"
    )
    created.append("tests/test_main.py")

    (base / "data" / ".gitkeep").write_text("")
    created.append("data/.gitkeep")

    (base / "logs" / ".gitkeep").write_text("")
    created.append("logs/.gitkeep")

    (base / "docs" / "usage.md").write_text(
        "# Usage\n\n```bash\npython3 -m src.main\n```\n"
    )
    created.append("docs/usage.md")

    return created


def print_bootstrap_summary(project_name: str, template_name: str, created_items):
    print(f"Bootstrap complete: {project_name}")
    print(f"Template used: {template_name}")
    print("")
    print("Created items:")
    for item in created_items:
        print(f"  - {item}")


def bootstrap(project_name: str, template_name: str):
    templates = {"python-cli", "python-library", "docs", "automation-tool"}

    if template_name not in templates:
        print(f"Unknown template: {template_name}")
        print("Available templates: python-cli, python-library, docs, automation-tool")
        return

    base = Path(project_name)

    if base.exists():
        print(f"Project already exists: {project_name}")
        return

    base.mkdir()
    created_items = [f"{project_name}/"]
    created_items.extend(write_common_files(base, project_name))

    if template_name == "python-cli":
        created_items.extend(bootstrap_python_cli(base, project_name))
    elif template_name == "python-library":
        created_items.extend(bootstrap_python_library(base, project_name))
    elif template_name == "docs":
        created_items.extend(bootstrap_docs(base, project_name))
    elif template_name == "automation-tool":
        created_items.extend(bootstrap_automation_tool(base, project_name))

    print_bootstrap_summary(project_name, template_name, created_items)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        show_help()
    else:
        command = sys.argv[1].lower()

        if command == "run":
            run()
        elif command == "version":
            version()
        elif command == "info":
            info()
        elif command == "status":
            status()
        elif command == "status-json":
            status_json()
        elif command == "config":
            config()
        elif command == "init":
            init()
        elif command == "doctor":
            doctor()
        elif command == "bootstrap":
            if len(sys.argv) < 4:
                print("Usage: python3 -m src.cli bootstrap <project-name> <template>")
                print("Available templates: python-cli, python-library, docs, automation-tool")
            else:
                bootstrap(sys.argv[2], sys.argv[3])
        elif command == "help":
            show_help()
        else:
            print(f"Unknown command: {command}")
            show_help()
